### ISSUE TITLE
Erreur - Produit - Lecture de la définition

### ISSUE THREAD

**Issue by vdegrandpre** [SplashSync/Php-Core#7]
**Client** : Dolibarr v 2.20.0

[Splash Client] Fatal Error: Argument 2 passed to Splash\Components\FieldsFactory::addChoice() must be of the type string, null given, called in / ... //htdocs/custom/splash/vendor/splash/phpcore/Components/FieldsFactory.php on line 551
[Splash Client] Location: / ... //htdocs/custom/splash/vendor/splash/phpcore/Components/FieldsFactory.php Line 565
[Splash Client] Full Trace Stack:
#0 / ... //htdocs/custom/splash/vendor/splash/phpcore/Components/FieldsFactory.php(551): Splash\Components\FieldsFactory->addChoice('', NULL)
#1 / ... //htdocs/custom/splash/src/Core/ExtraFieldsTrait.php(92): Splash\Components\FieldsFactory->addChoices(Array)
#2 / ... //htdocs/custom/splash/vendor/splash/phpcore/Models/Objects/IntelParserTrait.php(79): Splash\Local\Objects\Product->buildExtraFields()
#3 / ... //htdocs/custom/splash/vendor/splash/phpcore/Router/Objects.php(163): Splash\Local\Objects\Product->fields()
#4 / ... //htdocs/custom/splash/vendor/splash/phpcore/Router/Objects.php(61): Splash\Router\Objects::doAdminActions(Array)
#5 / ... //htdocs/custom/splash/vendor/splash/phpcore/Components/Router.php(140): Splash\Router\Objects::action(Array)
#6 / ... //htdocs/custom/splash/vendor/splash/phpcore/Components/Router.php(104): Splash\Components\Router->executeTask('\\Splash\\Router\\...', Array)
#7 / ... //htdocs/custom/splash/vendor/splash/phpcore/Server/SplashServer.php(365): Splash\Components\Router->execute('objects', Array, Array)
#8 / ... //htdocs/custom/splash/vendor/splash/phpcore/Server/SplashServer.php(137): Splash\Server\SplashServer::run('e039517c29c0010...', 'L05vQVVNL01LQ3J...', 'objects')
#9 / ... //htdocs/custom/splash/vendor/splash/phpcore/inc/server.inc.php(74): Splash\Server\SplashServer::objects('e039517c29c0010...', 'L05vQVVNL01LQ3J...')
#10 [internal function]: Objects('e039517c29c0010...', 'L05vQVVNL01LQ3J...')
#11 / ... //htdocs/custom/splash/vendor/splash/phpcore/Components/SOAP/SOAPInterface.php(162): SoapServer->handle('#12 / ... //htdocs/custom/splash/vendor/splash/phpcore/soap.php(73): Splash\Components\SOAP\SOAPInterface->handle()
#13 {main}

**Comment by BadPixxel** [comment]
Hi,

Thanks for reporting this issue. We fixed it in 2.3.11 release.
See [#c4689c40898746172e4d6ed7299f798849abf947](https://github.com/SplashSync/Php-Core/commit/c4689c40898746172e4d6ed7299f798849abf947)

Best regards,
